### ISSUE TITLE
Lack of Information on `run`  Variable in Kafka Consumer API

### ISSUE THREAD

**Issue by zakhaev26** [confluentinc/confluent-kafka-go#1117]
Description
===========

I am following the Confluent documentation to create a Kafka consumer in Go, and I noticed that the provided code lacks information about the 'run' variable. The code snippet is as follows:

```go
err = consumer.SubscribeTopics(topics, nil)

for run == true {
    ev := consumer.Poll(100)
    switch e := ev.(type) {
    case *kafka.Message:
        // application-specific processing
    case kafka.Error:
        fmt.Fprintf(os.Stderr, "%% Error: %v\n", e)
        run = false
    default:
        fmt.Printf("Ignored %v\n", e)
    }
}

consumer.Close()
```

The code uses a 'run' variable in the loop condition (for run == true), but there is no indication of how this variable is initialized or updated within the provided code snippet. This lack of information makes it challenging to understand the expected behavior of the loop and how to properly terminate it.

How to reproduce
================
N/A

Checklist
=========
Please provide the following information:

 - [ 1.9.2] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ 1.9.2] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ Ubuntu Linux ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
Hi @zakhaev26 , the getting started is only for a quick look at how the API itself works, rather than focusing on the other aspects. Please check the more detailed [examples ](https://github.com/confluentinc/confluent-kafka-go/tree/master/examples) linked in the README. 
The comment above the run variable mentions possible ways that users change it with. See this comment for more detail: https://github.com/confluentinc/confluent-kafka-go/pull/846#pullrequestreview-1171885355
