### ISSUE TITLE
Reprocessed messages after a Pause and Resume

### ISSUE THREAD

**Issue by eliaslevy** [confluentinc/confluent-kafka-go#192]
Description
===========

Calling `Resume` after `Pause` at times results in a previously consumed offset being re-consumed.

We have an application that pauses and resumed partitions.  It also keeps track of the last consumed offset to ensure they increase monotonically.  The app is using events channel.  This are some logs from the it:

It first receives a message with offset 36682 and decides to pause the partition:
```
2018/05/26 00:42:56 DEBUG Message on topic1[8]@36682
2018/05/26 00:42:56 DEBUG Pausing partition topic1[8]@36682.
```

It then receives a message with offset 36683 on the same partition.  The message was probably already buffered in the event channel:
```
2018/05/26 00:42:56 DEBUG Message on topic1[8]@36683
```

It then commits offsets:

```
2018/05/26 00:43:08 DEBUG Committing offsets for 42 partitions
2018/05/26 00:43:08 INFO delayed_events_1[8]@36682
```

It then decides to resume the partition:
```
2018/05/26 00:43:56 DEBUG Resuming paused partitions: [... topic1[8]@36682  ...]
```
I believe the offset in the resume operation has no effect.  Looking at the `librdkafka` library it seems to keep track of the next app offset based on the offset of the last message it placed on the internal rd queue and resumes from it.

It then receives the message at offset 36683 again:

```
2018/05/26 00:43:56 DEBUG Message on topic1[8]@36683
2018/05/26 00:43:56 ERROR Non-monotonic offsets in topic topic1, partition 8. Last offset 36683, next 36683
```

I believe this may be a separate issue from that described in #175.

How to reproduce
================

Not quite clear, as it seems to occur sporadically.  

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 721919 0.11.3
 - [x] Apache Kafka broker version: 0.11.0.1
 - [x] Client configuration: `ConfigMap{...}`:

```
&kafka.ConfigMap{
		"bootstrap.servers":               s.conf.Kafka.Servers,
		"client.id":                       s.conf.Kafka.ClientId,
		"group.id":                        s.conf.Kafka.GroupId,
		"session.timeout.ms":              s.conf.Kafka.SessionTimeoutMs,
		"go.events.channel.enable":        true,
		"go.application.rebalance.enable": true,
		"enable.auto.commit":              false,
		"default.topic.config":            kafka.ConfigMap{"auto.offset.reset": s.conf.Kafka.DefaultOffsets},
		"statistics.interval.ms":          1000,
		"queued.min.messages":             100,
		"fetch.wait.max.ms":               1000,
		"queued.max.messages.kbytes":      1000000,
		"socket.keepalive.enable":         true,
		"socket.nagle.disable":            true,
		"log.connection.close":            false,
	})
```
 - [x] Operating system: Linux, CentoOS 7
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The consumer channel API has proven troublesome due to the multiple queuing going on, there's discussion to deprecate and remove the channel API for this reason: #188, so I strongly suggest you to moving to the functional API instead.

--

Looking at your description above it seems to me the client is actually doing the right thing,
you pause on offset 36682, and when you resume get you 36683.
The fact that you get 36683 right after pause is due to the above channel issue.
What surprises me though is that you don't get message 36684 when you resume, which I would've expected since message 36683 was passed to the application.

When pausing the client stores the current app_offset ( which is the last message passed to the application + 1) as the next_offset. In the case of channels this could be a message that the application itself has not seen yet, which I think is the case with 36683.
On resuming the fetcher continues at next_offset (paused app_offset + 1).

**Comment by edenhill** [comment]
Most likely fixed in:
https://github.com/edenhill/librdkafka/issues/2455
https://github.com/edenhill/librdkafka/issues/2105
