### ISSUE TITLE
configure consumer with proxy

### ISSUE THREAD

**Issue by amikar** [confluentinc/confluent-kafka-go#242]
Description
===========
I am behind a firewall and trying to consume messages from topics which are using sasl_ssl security protocol .
I have configured the sasl information and it seems to work and I am able to consume messages in my local environment. But once I go behind the firewall I seem to be getting 

```
%7|1540495788.410|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress:in progress: no cluster connection
%7|1540495788.464|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: coordinator query
%7|1540495788.465|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: Group "superdome-group": no broker available for coordinator query: intervaled in state wait-broker
```
**_Is there a way to configure the firewall settings for the consumer by giving it the proxy information ?_** 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Upon bootstrapping to the cluster consumers will attempt to establish connections with the broker's `advertised.listeners`. If these addresses are not routable form the other side of the firewall then it will be impossible for your consumer to form a group or consume from kafka. 

Assuming all traffic must go through the proxy you could try the following: 

1. Set each broker's `advertised.listener` to the hostname of the proxy. Make sure each broker listens to a unique port
2. Configure your proxy to route requests to the appropriate broker by port number. 
3. Configure the broker's `listener.security.protocol.map` so that all `internal(replication traffic)` goes directly to the appropriate broker. This avoids unnecessary trips to the proxy and back. KIP-103, linked below explains how to separate internal from external traffic. 

https://cwiki.apache.org/confluence/display/KAFKA/KIP-103%3A+Separation+of+Internal+and+External+traffic
