### ISSUE TITLE
Question: is it possible to produce without replication and with unavailable partition

### ISSUE THREAD

**Issue by urusha** [confluentinc/confluent-kafka-go#363]
Description
===========
We have 2 brokers (1 down), topic wih replication_factor=1, partitions=2 (1 with no leader). It seems that example go producer waits for all partitions to be available before produce any message (at least with `kafka.PartitionAny`). `kafka-console-producer.sh` continues to work in such situation.
Is there a way to make producer work if there is at least one alive partition with unreplicated topic? Or there is a fast way to get alive partitions list and use ids with `Partition:` (special partitioner / code snippet)?

How to reproduce
================
See description.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 16843007 1.1.0-36-gb3223e
 - [x] Apache Kafka broker version: 2.12-2.3.0
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: debian 9 amd64
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
the default java partitioner chooses a partition at random from the set of available partitions, so will give the behavior you're looking for as you've observed (except for the edge case where the partition goes offline and the client is not aware of that yet).

the default librdkafka partitioner chooses a partition at random from the set of all partitions. if that partition is unavailable, it chooses another partition at random and uses that (regardless of whether that partition is available). so librdkafka sits somewhere in between a completely random distribution and only using available partitions. I've argued elsewhere that choosing either extreme as the default has merit (probably the behavior you want is the more commonly useful one, so that is a better default), but that the current behavior isn't exactly what anyone would want. Also I think we can probably change this without worrying about backwards compatibility. 

For now, you should be able to use the `GetMetadata` method to get the information required to achieve what you want manually.
