### ISSUE TITLE
Alan's review

### ISSUE THREAD

**Issue by edenhill** [confluentinc/confluent-kafka-go#5]
This issue references the points made by Alan @alanctgardner in his API review blog:
http://www.agardner.me/golang/kafka/library/sarama/confluent/2016/08/24/kafka-go-library.html

**Comment by ljackson** [comment]
From my testing the Channel producer is vastly more performant than the Function based one. Also so far this and librdkafka are at least 5x the thruput as Sarama's async producer in my testbed. I don't have anything publicly to share but I am voting for the Channel based Producer API with one small change I really need the Value at least to be an io.Reader interface and the returned event on the Events channel for success to keep this value as an io.Reader so I can return my custom buffer to a pool for performance rather than allocating it each time I need to send to the producer. anyone needing to send a []byte slice can just wrap that in a bytes.NewBuffer([]byte..) ...etc. Thanks

**Comment by ljackson** [comment]
I actually solved this using the Opaque field to carry a reference to the bytes.Buffer I was using so the Value could be the results from my var .Bytes()

**Comment by edenhill** [comment]
@ljackson Can you provide some example code snippets?

**Comment by polyma** [comment]
https://gist.github.com/savaki/a19dcc1e72cb5d621118fbee1db4e61f could be relevant.

**Comment by StevenACoffman** [comment]
@polyma Interesting! Do you happen to have the producer equivalent?
