### ISSUE TITLE
error is unavailable when creating consumer

### ISSUE THREAD

**Issue by AI-GQ** [confluentinc/confluent-kafka-go#579]
Description
===========
When i use wrong kafka configuration intentionally to create consumer (consumer_example.go), i find that return err is always 'nil'. However, terminal tells me the result and real reason. So, it is useless to check err nil after NewConsumer. Is this a bug? In fact, i need real err info to check in my code.
```
package main

import (
	"fmt"
	"gopkg.in/confluentinc/confluent-kafka-go.v1/kafka"
)

func main() {

	broker := "testip"
	group := "test"
	topics := []string{"test"}

	c, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers": broker,
		"broker.address.family": "v4",
		"group.id":              group,
		"session.timeout.ms":    6000,
		"auto.offset.reset":     "earliest"})

	fmt.Println(err)
	err = c.SubscribeTopics(topics, nil)
	fmt.Println(err)
	for {}
}
```
![image](https://user-images.githubusercontent.com/76587634/103151087-d568cd00-47b5-11eb-958d-34776099b6ca.png)

How to reproduce
================
Run consumer_example.go with wrong configuration and  check the err after NewConsumer.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): gopkg.in/confluentinc/confluent-kafka-go.v1 v1.5.2
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}` 
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
this isn't a bug, librdkafka assumes you got the configuration correct, and that `testip:9092` not being resolved is a temporary problem - if/when the bootstrap becomes available, librdkafka will automatically start using it.

i would personally like to see a constructor that blocks until it establishes a connection to a bootstrap server, and errors out if it can't - that matches how i want to use it. right now, you can achieve this by looking at errors emitted as you poll the consumer and reacting if the time since the application began is small enough.
