### ISSUE TITLE
how to config auto.offset.reset when  replace sarama using confluent client? 

### ISSUE THREAD

**Issue by in-the-sky-a** [confluentinc/confluent-kafka-go#647]
Description
===========

hi, currently we use sarama as kafka client, but we found some bugs, so want to replace sarama using confluent-kafka-go. 
In order to ensure that the migration does not lose messages, how to config auto.offset.reset and enable.auto.commit?
when I first online confluent-kafka-go , and I set auto.offset.reset=latest. Does it will read latest partition offset or read the offset commit by sarama client? 

According my test, it read the latest offset , this will lost message. how to config if I want to read the offset commit by sarama client ? I want to ensure not lost message. 

another question : do we need  set enable.auto.commit=true? 

How to reproduce
================
here is my consumer code :

var kafkaConf = &kafka.ConfigMap{
        "api.version.request": "true",
        "auto.offset.reset": "latest",
        "heartbeat.interval.ms": 3000,
        "session.timeout.ms": 30000,
        "max.poll.interval.ms": 120000,
        "fetch.max.bytes": 1024000,
        "max.partition.fetch.bytes": 256000}
    kafkaConf.SetKey("bootstrap.servers", *cfg.Address)
    kafkaConf.SetKey("group.id", *cfg.GroupId)
    kafkaConf.SetKey("security.protocol", "plaintext")

    consumer, err := kafka.NewConsumer(kafkaConf)
    if err != nil {
        panic(err)
    }

consumer.SubscribeTopics([]string{"test1", "test2"}, nil)

    for {
        message, err := consumer.ReadMessage(-1)
        if err == nil {
            log.println(message)
        } else {
            log.Errorf("consumer err %s" , err.Error())
        }
    }

**Comment by mhowlett** [comment]
`auto.offset.reset` is only relevant if there are no committed offsets for a partition of interest, or there was an error retrieving them - the value you set will not come into play. I would suggest setting this to `error`.

`enable.auto.commit` defaults to true. `enable.auto.offset.store` also defaults to true, which instructs librdkafka to mark offsets as eligible to commit immediately before delivering them to the application. because auto commits in librdkafka happen on a background thread, this provides neither at least once or at most once semantics. I would advise setting `enable.auto.offset.store` and calling store offsets after you have finished processing the message to get at least once semantics. Also, you need to store consumed message + 1 since by convention committed offsets represent the next message to consume.
