### ISSUE TITLE
How to know consumer is declared dead by broker

### ISSUE THREAD

**Issue by pritamlipu1** [confluentinc/confluent-kafka-go#716]
Description
===========
Sometimes coz of heartbeat expiration consumer is declared dead by consumer coordinator. And nothing is procesed after that. But service was up and running. Only consumer was declared dead by broker for strange reason, may be network issue or something. So We want to create a new consumer, once existing consumer is declared dead so that consumer will get connected again. And it will start receiving msgs/events.

In Prod cluster, nothing was processed and it affected customer. We had to restart service manually.

So We want consumer to get recovered automatically. Eg: once its dead (but service will be up), then we can create a new consumer.

Is there a way consumer can send something to broker to let it know its back?
Do we have a callback or something from consumer side so that we will know that current consumer is declared dead by broker and we can create a new consumer so that it will try to connect again?

Note: We fetch msgs through Events channel

**Comment by pritamlipu1** [comment]
@edenhill plz suggest

**Comment by jliunyu** [comment]
Hi @pritamlipu1, thanks for asking. I listed my answers for you questions below:

1. Is there a way consumer can send something to broker to let it know its back?
- When a new consumer joins to a group, then Kafka will trigger rebalancing for the group automatic. 
2. Do we have a callback or something from consumer side so that we will know that current consumer is declared dead by broker and we can create a new consumer so that it will try to connect again?
-  In the event consumer is unable to contact any of the brokers, an ErrAllBrokersDown err will be caught. But the client will try to automatically recover. After the retries have been exhausted, you'll need to decide what you want to do at this point. Here is an example for how to catch up this error for go client: https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/consumer_example/consumer_example.go#L93

**Comment by milindl** [comment]
Closing this as I think @jliunyu 's answer covers things, please reopen if there are more questions.
