### ISSUE TITLE
Bulk data requests to multiple channels

### ISSUE THREAD

**Issue by kostrahb** [confluentinc/confluent-kafka-go#75]
Is there any example how to process data from multiple channels but not by subscribing to all of the channels at once? I would prefer to look if there are any data in a channel and if there are any load them, make some computations, discard them and continue with next channel. Is that possible?
In the system is potentially a lot of data and I need group them by mac address and timestamp during the computations so the kafka is used in a similar fashion to first step of bucket sort. The data are divided to topics according to first three letters of mac address.

May I do something like adding c.UnsubscribeTopics(topics, ...) to case kafka.PartitionEOF in consumer channel example?

**Comment by edenhill** [comment]
It sounds like you want to split up seperate topic+partitions into separate channels so that you can consume N messages per partition.
This is currently not supported, but you can provide the fan-out yourself by consuming messages and then splitting them up into separate channels based on topic.
You might want to disable automatic offset stores (but not commits) and perform explicit offset stores to control exactly which message offsets are committed or not, see https://github.com/confluentinc/confluent-kafka-go/pull/72
