### ISSUE TITLE
What happens to the stored offsets if the partitions for a consumer get revoked ?

### ISSUE THREAD

**Issue by shubhang93** [confluentinc/confluent-kafka-go#756]
I am currently storing offsets manually using the `consumer.StoreOffsets` method but relying on the auto commit timer to commit my offsets every 5s, what will happen to my offsets if the partitions for the stored offsets get revoked before the commit happens ? 

Example:
Consumer `c1` when it starts gets assigned partitions `0,1` and `2`. After some processing I add offsets `10,11,12` of partition `0` to my stored offsets using `consumer.StoreOffsets` method. In the next second a new consumer c2 gets added to the group and partition `0` gets revoked from consumer `c1` and gets assigned to consumer `c2`. My concern is what will happen to the stored offsets `10,11,12` for `c1` ? Will they get committed when then auto-commit timer for c1 fires after `5s`

**Comment by edenhill** [comment]
That's an excellent question and very timely since we just fixed an issue with this modus operandi:

The stored offset is cleared when partitions are unassigned/revoked.
But, the application is allowed to store offsets for unassigned partitions, which thus overwrites the cleared offset with a valid offset, which will cause the auto-committer to commit that stored offset once the partition is assigned again.

This has been fixed in this PR: https://github.com/edenhill/librdkafka/pull/3774

**Comment by shubhang93** [comment]
So with `v1.8.2` the stored offsets are expected to be reset

**Comment by edenhill** [comment]
The fix in the PR is going into the next release, 1.9.0.

**Comment by shubhang93** [comment]
Understood, but is the reset behaviour present in `v1.8.2` as well ? I know that the `StoreOffsets` method will not return an error in the current version but will it at least reset the offsets on revoked partitions ?

**Comment by edenhill** [comment]
Yes, 1.8.2 will clear/reset the stored offset when partitions are unassigned/revoked.
