### ISSUE TITLE
What is the difference between using a rebalance callback and using the `go.application.rebalance.enable`

### ISSUE THREAD

**Issue by shubhang93** [confluentinc/confluent-kafka-go#761]
Can I do the same operations that I do inside the rebalance callback if I set the `go.application.rebalance.enable` and listen to the `Kafka.AssignedPartitions` and `Kafka.RevokedPartitions` during the poll.

Example:-
```golang
consumer.Subscribe(topics,func(consumer *kafka.Consumer, event kafka.Event)error {
 switch ev := e.(type) {
  case Kafka.AssignedPartitions:
   // do some things
  case kafka.RevokedPartitions:
   // do some things
 }
})

// In the poll loop
for {
 e := consumer.Poll(100)
 switch ev := e.(type) {
  case Kafka.AssignedPartitions:
   // do some things
  case kafka.RevokedPartitions:
   // do some things
 }
}
```
My question is, Are the above blocks of code equivalent ?

**Comment by jliunyu** [comment]
1) If you config `go.application.rebalance.enable`,  the second part the code above is okay, but if you don't use channel based consumer, please avoid this way because there is a know issue : https://github.com/confluentinc/confluent-kafka-go/issues/610

```// In the poll loop
for {
 e := consumer.Poll(100)
 switch ev := e.(type) {
  case Kafka.AssignedPartitions:
   // do some things
  case kafka.RevokedPartitions:
   // do some things
 }
}
```
2) For the rebalance callback, you can use this example as reference: https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/cooperative_consumer_example/cooperative_consumer_example.go

**Comment by shubhang93** [comment]
Thank you very much!
