### ISSUE TITLE
Consumer choose offset?

### ISSUE THREAD

**Issue by algorerhythm** [confluentinc/confluent-kafka-go#91]
Hi Magnus,

I'm writing an API that uses Kafka to cache the last N messages published to a topic. Ideally, clients would be able to choose the offset that they consume from each time they connect (ex. '/consume/\<topic\>/\<offset\>').

* Given this use case, would it be best to create a single consumer when the application starts or create a new consumer with a unique group.id for each request?

* I modelled my code after your "tailing consumer" gist (https://gist.github.com/edenhill/9dfc019b980a5eb3365c84524a1f12b0) and set "enable.auto.commit=false" as recommended in an issue on the librdkafka Github (https://github.com/edenhill/librdkafka/issues/593)

Any advice that you have will be greatly appreciated!

**Comment by edenhill** [comment]
Hi,

when you say the "the last N messages .. in a topic", how do you plan on handling partitions?
I'm guessing you want to abstract the notion of partitions to your clients, to do that you will first need to make your service gather the available partitions for a topic by using the Metadata() API.


If you are looking at caching all messages requested by connecting clients you should be fine with a single consumer.
As a client requests a partition and offset  and check if the requested offset is cached, if it is not you call Assign() with the full partition set of all topics and partitions you are caching (since I guess you want to pick up new messages of previously cached partitions too), making sure to set the new start offset of the (possibly partially) uncached partition.
When messages start rolling in you cache the uncached ones and discard the messages already in your cache.
This solution should scale well regardless of the number of connected clients, but is limited to how much data you are able to cache.

Do note that Assign() takes the absolute set of partitions to consume, replacing the current set, this effectively means that as soon as a client requests an offset that isn't cached there will be a short pause when the old assignment is torn down and the new one is instated. In this process any messages in internal librdkafka queues are also purged, so it might be wise to limit the number of pre-fetched messages by adjusting `queued.min.messages` (lower threshold) and `queued.max.messages.kbytes` (upper threshold).

And yeah, since this approach does not make use of committed offsets you should turn them off.

Not sure if that answered your questions?

**Comment by erik-stephens** [comment]
I have similar use case that I asked about in Blizzard/node-rdkafka#313.  Hoping someone more familiar with librdkafka than I can help me determine if I can use it for *consistent* consumption of a topic.  I emphasize *consistent* because it's important to be able to reprocess part of a topic.  I don't mind doing some of the heavy lifting like offset mgmt & consumer rebalancing.  I'm leaning on librdkafka for a) performance and b) not having to write my own client.  Thanks!

**Comment by edenhill** [comment]
There is no single ready-made API for what you want to do, but it should be fairly simple to use the existing APIs and holding some local state per partition yourself, something like this:

 1. given a set of partitions and an offset range (start..start+cnt, or start..end) per partition
 2. call `Assign()` with the above partition set with `.Offset` set to the starting offset.
 3. consume messages, one by one, map message to the correct local partition state
 4. update your local partition state with the last offset consumed, if the end offset of the range is reached ignore further messages for that partition and call `Pause()` to stop consumption.
 5. repeat 3 until all partition ranges are satisfied.
 6. call `Unassign()`
 7. go back to 1 eventually

**Comment by erik-stephens** [comment]
Thanks!  That's pretty much what I have planned.  My concerns/questions are around the details for steps 2 & 3.  My findings so far is that assigning to multiple partitions and calling consume yields inconsistent results - depends too much on buffer/queue settings as well where I'm at relative to the topic.  To be clear, I'm referring to points in time potentially far apart.  For example, at time T1 I might be consuming the end of the topic (streaming mode).  At time T2, I will want to reprocess a specific offset range (batch mode).  As a workaround, I could:

- assign(partition: 0)
- consume(n)
- assign(partition: 1)
- consume(n)
- ...

but that would require a broker round-trip for each assign()?  When you say consume "one by one", do you specifically mean `consume(1)`?  I understand that librdkafka pre-fetches so shouldn't require a broker round-trip, but still gives me pause for the volume I'm working with.

**Comment by edenhill** [comment]
For performance you should typically assign the entire partition set at once in step 2 and perform demuxing from consume()/poll() yourself, as described in step 3.

When you want to stream you simply set the start offset to OFFSET_END, and when you want to replay a previous range you set the absolute offset to start for each partition.

assign() will not require an extra roundtrip if you specify absolute starting offsets, but logical starting offsets will require one roundtrip per partition to resolve the logical (beginning,end,..) to absolute offset.

Since librdkafka prefetches messages (which you've noticed) until `queued.min.messages` or `queued.max.messages.kbytes` is reached (NOT per partition, but for all assigned partitions combined), you want to make sure that the fetched partitions are somewhat evenly added to that queue - to do this you would typically reduce the fetch size per partition `fetch.message.max.bytes` to be `queued.max.messages.kbytes / num_partitions_assigned`. But it may take some tweaking to find a perfect value (`debug=fetch` is convenient to see when and why partitions are fetched or not).
